import {
  nature,
  peace,
  challenge,
  food,
  hikers,
  goat,
} from "../assets/index.js";

export const testimonials = [
  {
    index: 1,
    alt: "nature",
    image: nature,
    name: "John Doe",
    text: "Whether up on the mountain or down by the sea, the natural environment is a source of inspiration and healing. We will be spending time in both locations, to experience the best of both worlds.",
  },
  {
    index: 2,
    alt: "peace",
    image: peace,
    name: "John Doe",
    text: "The retreat is designed to be a time and space for people-centered professionals to relax, reflect, recharge and connect with kindred spirit professionals. Activities will be focused on self-care and development as well as community relationship building, with plenty of time to rest and enjoy the surroundings.",
  },
  {
    index: 3,
    alt: "group of hikers",
    image: hikers,
    name: "John Doe",
    text: "The retreat is invite-only, offering you the opportunity to engage with a remarkable and diverse group of like-minded individuals. If I’ve invited you, it's because I admire and like you and would love to stay connected over the years as we all pursue our own paths. ",
  },
  {
    index: 4,
    alt: "food",
    image: food,
    name: "John Doe",
    text: "Apart from local Greek & Mediterranean cuisine options available - I will personally prepare 2 delicious feasts, using a traditional brick oven with the oversight and help of a special seasoned chef.",
  },
  {
    index: 5,
    alt: "hiker climbing Mount Olympus",
    image: challenge,
    name: "John Doe",
    text: "All fitness levels welcome. This is not a competition. The hike is planned so that we are challenged but remain safe and focused on what is most important: enjoyment and relationship building.",
  },
  {
    index: 6,
    alt: "goat",
    image: goat,
    name: "John Doe",
    text: "The chamois, wild goats that live in Alpine terrains in Europe, can be seen at the Plateau of Muses, surrounded by green and tranquility. Actual goats are not included in the retreat, but they are welcome to join!",
  },
  {
    index: 7,
    alt: "goat",
    image: goat,
    name: "John Doe",
    text: "The chamois, wild goats that live in Alpine terrains in Europe, can be seen at the Plateau of Muses, surrounded by green and tranquility. Actual goats are not included in the retreat, but they are welcome to join!",
  },
  {
    index: 8,
    alt: "goat",
    image: goat,
    name: "John Doe",
    text: "The chamois, wild goats that live in Alpine terrains in Europe, can be seen at the Plateau of Muses, surrounded by green and tranquility. Actual goats are not included in the retreat, but they are welcome to join!",
  },
  {
    index: 9,
    alt: "goat",
    image: goat,
    name: "John Doe",
    text: "The chamois, wild goats that live in Alpine terrains in Europe, can be seen at the Plateau of Muses, surrounded by green and tranquility. Actual goats are not included in the retreat, but they are welcome to join!",
  },
  {
    index: 10,
    alt: "goat",
    image: goat,
    name: "John Doe",
    text: "The chamois, wild goats that live in Alpine terrains in Europe, can be seen at the Plateau of Muses, surrounded by green and tranquility. Actual goats are not included in the retreat, but they are welcome to join!",
  },
  {
    index: 11,
    alt: "goat",
    image: goat,
    name: "John Doe",
    text: "The chamois, wild goats that live in Alpine terrains in Europe, can be seen at the Plateau of Muses, surrounded by green and tranquility. Actual goats are not included in the retreat, but they are welcome to join!",
  },
];
